'use strict';
const $=id=>document.getElementById(id),M=ArcadeMath;
let game=new URLSearchParams(location.search).get('game')||'factors';if(!['factors','nim','line'].includes(game))game='factors';
let turn,last,used,owners,piles,over,round,score,tasks,timer,busy;
const content={factors:['약수·배수 연결 대결','사용하지 않은 수 중 직전 수의 약수 또는 배수를 고르세요. 첫 수는 자유입니다. 다음 수를 고를 수 없는 사람이 패배합니다.','중1 수와 연산 · 2인 또는 컴퓨터 · 5~10분. 질문: 소수를 고르면 다음 선택은 어떻게 달라질까요?'],nim:['님(Nim) 전략게임','한 차례에 한 줄에서 돌을 1개 이상 가져갑니다. 줄의 k번째 돌을 누르면 왼쪽부터 k개를 가져갑니다. 마지막 돌을 가져가는 사람이 승리합니다.','논리·추론 · 2인 또는 컴퓨터 · 5분. 질문: 같은 크기 두 줄만 남았을 때 어떤 전략이 있을까요?'],line:['일차함수 좌표 미션','주어진 일차함수에서 지정된 x에 대응하는 점을 좌표판에서 고르세요. 위쪽은 y=5, 오른쪽은 x=5입니다. 총 10문항입니다.','중2 일차함수 · 개인 · 5분. 질문: 기울기의 부호에 따라 그래프가 어떻게 달라질까요?']};
function start(){clearTimeout(timer);turn=1;last=0;used=[];owners={};piles=[3,5,7];over=false;busy=false;round=0;score=0;tasks=M.missions();$('title').textContent=content[game][0];$('rules').textContent=content[game][1];$('guide').textContent=content[game][2];$('feedback').textContent='';$('mode-label').hidden=game==='line';$('size-label').hidden=game!=='factors';document.querySelectorAll('[data-game]').forEach(b=>b.classList.toggle('active',b.dataset.game===game));render();}
function status(text){$('status').textContent=text;}
function button(text,fn,disabled=false){const b=document.createElement('button');b.textContent=text;b.disabled=disabled;b.onclick=fn;return b;}
function render(){const board=$('board');board.replaceChildren();board.className=game==='factors'?'':game;if(game==='factors'){const max=+$('size').value,legal=M.moves(last,used,max);for(let n=1;n<=max;n++){const b=button(n,()=>takeNumber(n),over||busy||!legal.includes(n));if(owners[n])b.className='p'+owners[n];b.setAttribute('aria-label',n+(owners[n]?' 플레이어 '+owners[n]+' 선택':''));board.append(b);}if(!over)status(`플레이어 ${turn} 차례 · ${last?'직전 수 '+last:'첫 수를 선택하세요'}`);}else if(game==='nim'){piles.forEach((n,row)=>{const div=document.createElement('div');div.className='pile';const label=document.createElement('strong');label.textContent=`${row+1}줄 (${n})`;div.append(label);for(let k=1;k<=n;k++){const b=button('●',()=>takeStones(row,k),over||busy);b.setAttribute('aria-label',`${row+1}줄에서 ${k}개 가져가기`);div.append(b);}board.append(div);});if(!over)status(`플레이어 ${turn} 차례`);}else{if(over){status(`미션 완료! ${score} / 10점`);board.append(button('다시 도전',start));return;}const q=tasks[round];status(`${round+1}/10 · y = ${q.a}x ${q.b<0?'−':'+'} ${Math.abs(q.b)} · x = ${q.x}`);for(let y=5;y>=-5;y--)for(let x=-5;x<=5;x++){const b=button(`${x},${y}`,()=>answer(x,y));if(x===0||y===0)b.className='axis';b.setAttribute('aria-label',`좌표 (${x}, ${y})`);board.append(b);}}}
function next(){turn=3-turn;if($('mode').value==='cpu'&&turn===2&&!over){busy=true;render();timer=setTimeout(()=>{busy=false;if(game==='factors'){const legal=M.moves(last,used,+$('size').value);legal.sort((a,b)=>M.moves(a,[...used,a],+$('size').value).length-M.moves(b,[...used,b],+$('size').value).length);takeNumber(legal[0]);}else{const m=M.nimMove(piles);takeStones(m.row,m.count);}},550);}else render();}
function takeNumber(n){if(over||busy||!M.moves(last,used,+$('size').value).includes(n))return;const previous=last;used.push(n);owners[n]=turn;last=n;$('feedback').textContent=previous?`${Math.max(previous,n)} ÷ ${Math.min(previous,n)} = ${Math.max(previous,n)/Math.min(previous,n)} · 연결 성공`:`첫 수: ${n}`;if(!M.moves(last,used,+$('size').value).length){over=true;status(`플레이어 ${turn} 승리! 상대가 선택할 수 있는 수가 없습니다.`);render();}else next();}
function takeStones(row,count){if(over||busy||!Number.isInteger(count)||count<1||count>piles[row])return;piles[row]-=count;$('feedback').textContent=`플레이어 ${turn}: ${row+1}줄에서 ${count}개 가져감`;if(piles.every(n=>n===0)){over=true;status(`플레이어 ${turn} 승리! 마지막 돌을 가져갔습니다.`);render();}else next();}
function answer(x,y){const q=tasks[round],correct=x===q.x&&y===q.y;if(correct)score++;$('feedback').textContent=`${correct?'정답!':'다시 확인해 보세요.'} y = ${q.a} × (${q.x}) + (${q.b}) = ${q.y}, 정답 좌표 (${q.x}, ${q.y})`;round++;over=round===10;render();}
$('hint').onclick=()=>{if(over)return;if(game==='factors')$('feedback').textContent='선택 가능한 수: '+M.moves(last,used,+$('size').value).join(', ');else if(game==='nim'){const m=M.nimMove(piles);$('feedback').textContent=`추천: ${m.row+1}줄에서 ${m.count}개. 각 줄의 돌 개수를 이진수로 나타내고 XOR 값을 0으로 만드는 전략을 탐구해 보세요.`;}else $('feedback').textContent='주어진 x를 식에 대입하세요. 먼저 x축에서 위치를 찾고 계산한 y만큼 위 또는 아래로 이동하세요.';};
$('reset').onclick=start;$('mode').onchange=start;$('size').onchange=start;document.querySelectorAll('[data-game]').forEach(b=>b.onclick=()=>{game=b.dataset.game;history.replaceState(null,'','?game='+game);start();});start();
