/* Published games are research candidates, not a claim that every game is implemented. */
window.BOARDGAME_CATALOG=[
 {id:'quarto',name:'콰르토',english:'Quarto',grades:['common','2'],domains:['reasoning','chance'],phase:1,status:'ready',mark:'2⁴',
  core:'상대에게 줄 말을 고르고, 네 가지 속성 중 하나가 같은 말 네 개를 한 줄로 만듭니다.',
  connection:'공통: 속성 분류와 전략 설명. 중2: 곱의 법칙으로 16종의 말을 세고 조건에 맞는 선택지를 셉니다.',
  standards:['[9수04-05] 경우의 수'],activity:'밝고 높은 말은 몇 개인가요? 상대가 바로 이길 수 없는 말을 빠짐없이 찾아 설명해 보세요.',
  adaptation:'기본 2인 규칙으로 구현했습니다. 승리를 자동 판정하며 고급 2×2 규칙은 제외합니다. 연습 · AI 3단계 · 같은 기기 2인을 지원합니다.',
  href:'../attribute-four/index.html',linkText:'지금 플레이',sources:[['Gigamic · 원작','https://en.gigamic.com/modern-classics/1049-quarto-3421271300410.html'],['공식 규칙','https://en.gigamic.com/index.php?controller=attachment&id_attachment=466']]},
 {id:'prime-climb',name:'프라임 클라임',english:'Prime Climb',grades:['1'],domains:['number'],phase:1,status:'planned',mark:'2·3·5',
  core:'주사위 수로 사칙연산을 하여 수판 위 말을 움직이는 수 연산 게임입니다.',
  connection:'중1: 수의 소인수 구조를 읽습니다. 공약수·공배수는 말의 위치를 이용한 추가 탐구로 연결합니다.',
  standards:['[9수01-01] 소인수분해','[9수01-02] 최대공약수·최소공배수'],activity:'두 말이 놓인 수를 소인수분해하고, 두 수의 공통 소인수를 색이나 표로 나타내 보세요.',
  adaptation:'제작 예정: 수판과 소인수 시각화를 독자적으로 제작하고 연산 연습, 난이도별 AI, 2인 대결을 구성합니다.',sources:[['Math for Love · 원작','https://mathforlove.com/product/prime-climb/']]},
 {id:'lost-cities',name:'로스트 시티',english:'Lost Cities',grades:['1','2'],domains:['number','relation'],phase:1,status:'planned',mark:'−20',
  core:'숫자가 커지는 순서로 탐험 카드를 놓고, 투자와 탐험 비용을 반영해 점수를 계산합니다.',
  connection:'중1: 양수·음수가 있는 점수 계산. 중2 확장: 이익이 나는 최소 카드 합을 부등식으로 나타냅니다.',
  standards:['[9수01-05] 정수·유리수의 사칙계산','[9수02-01] 문자를 사용한 식','[9수02-12] 일차부등식'],activity:'카드 합을 x라 두고 탐험 점수를 식으로 표현해 보세요. 투자 배수가 바뀌면 손익분기점도 바뀔까요?',
  adaptation:'제작 예정: 기존 2인 구조를 활용합니다. 연습은 점수 계산과 카드 선택 이유 설명으로 구성합니다.',sources:[['Thames & Kosmos · 원작','https://www.thamesandkosmos.co.uk/product/lost-cities-card-game/']]},
 {id:'rummikub',name:'루미큐브',english:'Rummikub',grades:['common','1'],domains:['number','reasoning'],phase:1,status:'planned',mark:'3·4·5',
  core:'같은 숫자의 묶음이나 같은 색의 연속된 숫자 묶음을 만들고, 놓인 타일을 재배열합니다.',
  connection:'공통: 조건 분류와 재구성. 중1 도입: 수의 순서 감각을 다지되 양의 정수 타일만으로 음수·유리수 전체를 배운다고 보지 않습니다.',
  standards:['[9수01-04] 정수·유리수의 대소 관계 — 도입 활동'],activity:'같은 타일을 모두 사용하면서 다른 합법적인 묶음을 만들 수 있나요? 각 묶음이 조건을 만족하는지 설명해 보세요.',
  adaptation:'제작 예정: 한 화면 2인 대결에서는 비공개 패를 가리는 기기 전달 화면이 필요합니다. AI 난이도는 재배열 탐색 범위를 조절합니다.',sources:[['코리아보드게임즈 · 게임 소개','https://www.koreaboardgames.com/magazine/menuDetail?boardCd=contents&postNo=256']]},
 {id:'no-thanks',name:'노 땡스!',english:'No Thanks!',grades:['1','2'],domains:['number','relation'],phase:1,status:'related',mark:'− / +',
  core:'불리한 점수 카드를 받을지 칩을 내고 넘길지 고릅니다. 연속된 숫자 카드의 점수 규칙을 함께 고려합니다.',
  connection:'중1: 카드와 칩을 반영한 점수식. 중2 확장: 두 선택의 점수 차이를 식과 부등식으로 비교합니다.',
  standards:['[9수02-01] 문자를 사용한 식','[9수02-12] 일차부등식 — 추가 탐구'],activity:'카드 한 장을 받을 때 총점이 얼마나 변하나요? 바로 앞·뒤 숫자를 가지고 있는 경우와 비교해 보세요.',
  adaptation:'원작은 3~7인입니다. AI 1명 및 같은 기기 2인용은 수업용 변형 규칙으로 별도 설계할 예정입니다. 기존 마이너스 경매는 관련 활동이며 원작과 동일하다고 보지 않습니다.',
  href:'../minus-auction/index.html',linkText:'관련 기존 활동',sources:[['CMYK · 원작','https://www.cmyk.games/products/no-thanks']]},
 {id:'cant-stop',name:'캔트 스탑',english:"Can't Stop",grades:['2','3'],domains:['chance'],phase:2,status:'planned',mark:'2d6',
  core:'주사위 네 개를 두 쌍으로 묶어 전진합니다. 계속 굴릴지 멈출지를 선택합니다.',
  connection:'중2: 두 주사위의 합과 경우의 수·확률. 중3: 반복한 결과의 산포를 비교하는 추가 통계 활동.',
  standards:['[9수04-05] 경우의 수','[9수04-06] 확률','[9수04-07] 분산·표준편차 — 추가 활동'],activity:'두 주사위의 합이 6인 경우와 7인 경우를 순서쌍으로 모두 적어 보세요. 실험의 상대도수와 비교해 보세요.',
  adaptation:'제작 예정: 연습은 주사위 조합 탐색, AI는 위험 감수 기준을 조절합니다. 2인 대결과 판별 점수 기록을 함께 제공합니다.',sources:[['Eagle-Gryphon Games · 원작','https://www.eagle-gryphon.com/products/cant-stop-1']]},
 {id:'qwixx',name:'큐윅스',english:'Qwixx',grades:['2','3'],domains:['chance'],phase:2,status:'planned',mark:'Σ',
  core:'주사위의 합으로 숫자를 지워 나가며, 지운 칸 수와 벌점을 반영해 점수를 얻습니다.',
  connection:'중2: 주사위 합의 확률. 중3 확장: 여러 판의 최종 점수를 상자그림으로 비교합니다.',
  standards:['[9수04-06] 확률','[9수04-08] 상자그림 — 추가 활동'],activity:'점수가 비슷한 두 전략 중 결과가 더 고르게 나오는 전략은 무엇인가요? 반복 기록을 모아 상자그림을 만들어 보세요.',
  adaptation:'제작 예정: 동시 선택 절차를 같은 기기의 순차 입력으로 바꾸되 각 사람의 선택 기회를 유지합니다.',sources:[['NSV · 공식 규칙','https://www.nsv.de/wp-content/uploads/2024/04/QwixxWuerfel_GB.pdf'],['NSV · 자료실','https://www.nsv.de/en/infocenter/']]},
 {id:'yahtzee',name:'얏찌',english:'Yahtzee',grades:['2','3'],domains:['chance'],phase:2,status:'planned',mark:'⚄',
  core:'다섯 주사위를 일부 다시 굴리며 점수표의 조합을 완성합니다.',
  connection:'중2: 단순한 주사위 사건의 경우의 수·확률. 중3: 전략별 점수 분포와 산포 비교.',
  standards:['[9수04-05] 경우의 수','[9수04-06] 확률','[9수04-07] 분산·표준편차','[9수04-08] 상자그림'],activity:'주사위 하나를 다시 굴려 원하는 눈을 얻는 확률부터 시작하세요. 복잡한 조합은 실험으로 비교합니다.',
  adaptation:'제작 예정: 재굴림 연습, 위험 선호가 다른 AI, 같은 기기 2인 순차 대결과 기록표를 만듭니다. 조합 공식은 필수로 요구하지 않습니다.',sources:[['Hasbro · 공식 설명서','https://instructions.hasbro.com/en-us/instruction/yahtzee']]},
 {id:'sagrada',name:'사그라다',english:'Sagrada',grades:['common','2'],domains:['reasoning','chance'],phase:4,status:'planned',mark:'◈',
  core:'색과 숫자, 인접 조건을 만족하도록 주사위를 골라 창문 판에 배치합니다.',
  connection:'공통: 여러 조건을 동시에 확인하는 추론. 중2 확장: 특정 칸에 들어갈 수 있는 주사위 조건의 경우를 셉니다.',
  standards:['[9수04-05] 경우의 수 — 추가 탐구'],activity:'한 칸에 허용되는 색과 눈을 표로 정리해 보세요. 두 조건을 함께 적용할 때 빠뜨린 경우가 있나요?',
  adaptation:'제작 예정: 기본 주사위 배치부터 구현하고 도구 카드·목표 카드는 단계적으로 확장합니다. 2인과 AI는 같은 공개 정보를 사용합니다.',sources:[['Floodgate Games · 원작','https://floodgate.games/products/sagrada-classic']]},
 {id:'blokus',name:'블로커스',english:'Blokus',grades:['common','1'],domains:['geometry','reasoning'],phase:3,status:'planned',mark:'▙',
  core:'여러 모양의 조각을 같은 색끼리 꼭짓점만 닿도록 놓아 공간을 차지합니다.',
  connection:'공통: 공간 감각과 배치 추론. 중1 확장: 조각을 다각형으로 보고 변·각·둘레를 조사합니다.',
  standards:['[9수03-05] 다각형의 성질 — 추가 탐구'],activity:'같은 넓이를 가진 조각의 둘레가 항상 같은가요? 오목한 꼭짓점을 포함해 조각의 각을 살펴보세요.',
  adaptation:'제작 예정: 조각 회전·뒤집기와 놓을 수 있는 자리 표시를 연습에 제공합니다. 원작의 2인 규칙을 선택하고 사용 색 수를 명시합니다.',sources:[['Mattel · 원작','https://shopping.mattel.com/en-gb/products/blokus-game-bjv44-en-gb']]},
 {id:'ubongo',name:'우봉고',english:'Ubongo',grades:['common','1','2'],domains:['geometry'],phase:3,status:'planned',mark:'▦',
  core:'주어진 평면 조각을 돌리고 뒤집어 정해진 공간을 빈틈없이 채웁니다.',
  connection:'공통: 공간 감각. 중1: 도형의 모양 비교. 중2 확장: 같은 모양의 확대 판을 만들어 닮음비를 비교합니다.',
  standards:['[9수03-12] 도형의 닮음 — 확대 판을 쓰는 추가 활동'],activity:'조각 전체를 두 배로 확대하면 필요한 넓이는 몇 배가 되나요? 원래 판과 확대 판을 겹쳐 설명해 보세요.',
  adaptation:'제작 예정: 독자적인 퍼즐 문제를 제작합니다. 한 기기에서는 두 사람이 같은 문제를 순차로 풀고 이동 수를 비교하는 수업용 대결로 구성합니다.',sources:[['Thames & Kosmos · 원작','https://www.thamesandkosmos.co.uk/product/ubongo/'],['공식 교사용 자료','https://thamesandkosmos.com/images/tip_sheets/Ubongo_Teacher_Tip_Sheet.pdf']]},
 {id:'ubongo-3d',name:'우봉고 3D',english:'Ubongo 3D',grades:['common','1'],domains:['geometry'],phase:3,status:'planned',mark:'▧³',
  core:'입체 블록을 조합하여 주어진 공간을 정해진 높이까지 채웁니다.',
  connection:'중1: 입체도형 탐색. 단위 정육면체로 블록을 해석하여 겉넓이와 부피를 비교하는 추가 활동.',
  standards:['[9수03-07] 입체도형의 성질','[9수03-08] 겉넓이·부피 — 추가 활동'],activity:'단위 정육면체 수가 같아도 겉넓이는 달라질까요? 맞닿아 사라지는 면을 세어 설명해 보세요.',
  adaptation:'제작 예정: 독자 문제와 층별 2D 보기를 먼저 제공합니다. 연습·AI 기준 기록·2인 순차 퍼즐 대결로 설계합니다.',sources:[['Thames & Kosmos · 원작','https://www.thamesandkosmos.co.uk/product/ubongo-3d/']]},
 {id:'kingdomino',name:'킹도미노',english:'Kingdomino',grades:['1','3'],domains:['relation','chance'],phase:4,status:'planned',mark:'A×C',
  core:'지형 타일을 연결하고 같은 지형의 영역 크기와 왕관 수를 곱해 점수를 계산합니다.',
  connection:'중1: 영역의 칸 수와 왕관 수를 문자로 나타낸 점수식. 중3 확장: 배치 전략별 최종 점수의 산포 비교.',
  standards:['[9수02-01] 문자를 사용한 식','[9수04-07] 분산·표준편차 — 추가 활동'],activity:'영역의 크기를 a, 왕관 수를 b라 할 때 점수는 어떻게 나타내나요? 어느 영역에 한 칸을 더 붙이는 것이 유리할까요?',
  adaptation:'제작 예정: 기본 2인 규칙과 공개 타일 선택을 바탕으로 연습·AI·같은 기기 대결을 구성합니다.',sources:[['Blue Orange · 원작','https://blueorangegames.eu/en/games/kingdomino/']]},
 {id:'qwirkle',name:'큐위클',english:'Qwirkle',grades:['common','2'],domains:['reasoning','chance'],phase:1,status:'planned',mark:'● ■',
  core:'색 또는 모양을 맞추되 중복 없이 타일을 이어 놓습니다.',
  connection:'공통: 두 속성에 따른 분류와 조건 검토. 중2 확장: 색·모양의 곱으로 타일 종류를 세어 봅니다.',
  standards:['[9수04-05] 경우의 수 — 추가 탐구'],activity:'색과 모양을 각각 하나씩 고르는 모든 타일 종류를 표로 정리하세요. 합법적인 줄과 불가능한 줄을 구분해 보세요.',
  adaptation:'제작 예정: 연습에서 합법 배치를 판단하고, 대결에서는 패를 가리는 기기 전달 화면과 AI 수 탐색을 제공합니다.',sources:[['MindWare · 원작','https://www.mindware.orientaltrading.com/qwirkle-tile-matching-game-award-winning-strategy-game-for-family-game-night-a2-32016.fltr']]},
 {id:'rush-hour',name:'러시아워',english:'Rush Hour',grades:['common','1'],domains:['reasoning','relation'],phase:3,status:'planned',mark:'→',
  core:'차량을 앞뒤로 움직여 목표 차량이 나갈 길을 만드는 1인용 퍼즐입니다.',
  connection:'공통: 순서 계획과 문제 해결. 중1 확장: 격자에 좌표를 붙여 차량 위치와 이동을 표현합니다.',
  standards:['[9수02-05] 순서쌍·좌표 — 좌표판을 덧붙인 활동'],activity:'차량의 시작 칸과 이동 후 칸을 좌표로 쓰세요. 같은 배치에 이르는 불필요한 왕복 이동을 찾을 수 있나요?',
  adaptation:'원작은 1인용입니다. 제작 시 독자 문제로 AI 풀이 기록과 겨루기, 두 사람의 동일 문제 최소 이동 대결을 추가하는 수업용 변형임을 표시합니다.',sources:[['Ravensburger / ThinkFun · 원작','https://www.ravensburger.us/en-US/products/games/thinkfun/rush-hour-76582']]},
 {id:'set',name:'세트',english:'SET',grades:['common','2'],domains:['reasoning','chance'],phase:1,status:'related',mark:'3⁴',
  core:'네 속성 각각에서 모두 같거나 모두 다른 세 카드를 찾습니다.',
  connection:'공통: 속성별 조건 검토. 중2 확장: 네 속성의 선택으로 카드 종류가 81개임을 설명합니다.',
  standards:['[9수04-05] 경우의 수 — 추가 탐구'],activity:'두 카드가 정해졌을 때 조건을 만족하는 세 번째 카드의 속성을 하나씩 설명해 보세요.',
  adaptation:'기존 세트 활동을 연결합니다. 현재 모드가 새 공통 기준을 모두 갖췄다고 보지는 않으며, AI 난이도와 같은 기기 순차 대결은 보강 대상입니다.',
  href:'../set-game/index.html',linkText:'기존 세트 활동',sources:[['SET · 공식 수학 활동 자료','https://www.setgame.com/sites/default/files/teacherscorner/mathworkbook_0.pdf']]},
 {id:'quoridor',name:'쿼리도',english:'Quoridor',grades:['common','1','2'],domains:['reasoning','relation','chance'],phase:3,status:'related',mark:'↗',
  core:'말을 움직이거나 벽을 놓아 상대보다 먼저 반대편에 도착합니다. 경로를 완전히 막을 수는 없습니다.',
  connection:'공통: 경로 추론. 중1 확장: 좌표로 이동 표현. 중2 확장: 작은 격자에서 제한된 경로의 수 세기.',
  standards:['[9수02-05] 순서쌍·좌표 — 추가 활동','[9수04-05] 경우의 수 — 작은 격자 탐구'],activity:'작은 격자에서 오른쪽과 위쪽으로만 이동할 때의 경로를 그림으로 모두 세어 보세요. 벽 하나를 놓으면 무엇이 달라지나요?',
  adaptation:'기존 게임 저장소의 활동을 연결합니다. 연습·AI 3단계·같은 기기 2인이라는 공통 기준 충족 여부와 보강은 이후 작업으로 남깁니다.',
  href:'https://jbmath-dot.github.io/game/%EC%BF%BC%EB%A6%AC%EB%8F%84.html',linkText:'관련 기존 게임 ↗',sources:[['Gigamic · 원작','https://en.gigamic.com/modern-classics/107-quoridor.html']]},
 {id:'splendor',name:'스플렌더',english:'Splendor',grades:['1','2'],domains:['relation','reasoning'],phase:4,status:'planned',mark:'x ≥ a',
  core:'자원을 모아 개발 카드를 구입하고, 지속되는 할인과 점수를 쌓습니다.',
  connection:'중1: 자원과 가격의 관계를 식으로 표현. 중2 확장: 할인 후 구매 조건을 부등식으로 나타냅니다.',
  standards:['[9수02-01] 문자를 사용한 식','[9수02-12] 일차부등식 — 추가 탐구'],activity:'가격 p, 할인 d, 보유 자원 x를 이용하여 구매할 수 있는 조건을 나타내 보세요. 여러 색은 각각 조건을 따로 확인합니다.',
  adaptation:'제작 예정: 기본 자원·할인 흐름부터 구성합니다. 수업용 축약 규칙은 원작과 구분하고, AI와 2인에 같은 조건을 적용합니다.',sources:[['Space Cowboys · 원작','https://www.spacecowboys-games.com/game/splendor/']]}
];
